
<?php
session_start();

if (!isset($_SESSION['cashiers_id'])) {
    header("Location: ../index.php");
    exit();
}

// Database connection
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "kidsberry";

$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) die("Connection failed: " . $conn->connect_error);

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['bill_no'])) {
    $bill_no = mysqli_real_escape_string($conn, $_POST['bill_no']);
    
    // Get bill details
    $bill_sql = "SELECT 
                    b.*,
                    c.name as cashier_name,
                    DATE(b.date) as bill_date,
                    TIME(b.date) as bill_time
                  FROM bills2 b
                  JOIN cashier_users2 c ON b.cashier_id = c.cashier_id
                  WHERE b.bill_no = '$bill_no'";
    $bill_result = $conn->query($bill_sql);
    
    if ($bill_result->num_rows === 0) {
        die("Bill not found");
    }
    
    $bill = $bill_result->fetch_assoc();
    
    // Get bill items
    $items_sql = "SELECT 
                    bi.*,
                    p.color as product_color
                  FROM bill_items2 bi
                  LEFT JOIN products p ON bi.product_id = p.product_id
                  WHERE bi.bill_no = '$bill_no'
                  ORDER BY bi.id";
    $items_result = $conn->query($items_sql);
    
    // Set headers for Excel download
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="bill_' . $bill_no . '_' . date('Y-m-d') . '.xls"');
    
    echo "KIDS BERRY - BILL DETAILS\n";
    echo "==========================\n\n";
    
    echo "Bill Number: " . $bill['bill_no'] . "\n";
    echo "Date: " . $bill['bill_date'] . "\n";
    echo "Time: " . $bill['bill_time'] . "\n";
    echo "Sales Officer: " . $bill['cashier_name'] . "\n";
    echo "Payment Method: " . $bill['payment_method'] . "\n";
    echo "Customer Name: " . ($bill['customer_name'] ?: 'Walk-in Customer') . "\n";
    echo "Phone: " . ($bill['phone_no'] ?: 'N/A') . "\n";
    echo "NIC: " . ($bill['nic_no'] ?: 'N/A') . "\n\n";
    
    echo "ITEMS DETAILS\n";
    echo "=============\n";
    echo "Product\tIMEI/PSN\tColor\tQty\tPrice\tDiscount\tTotal\tStatus\n";
    
    while ($item = $items_result->fetch_assoc()) {
        $status = $item['return_status'] === 'returned' ? 'Returned' : 'Sold';
        $item_total = ($item['price'] * $item['quantity']) - $item['discount'];
        
        echo $item['product_name'] . "\t";
        echo ($item['imei'] ?: $item['psn_numbers'] ?: 'N/A') . "\t";
        echo ($item['product_color'] ?: '') . "\t";
        echo $item['quantity'] . "\t";
        echo $item['price'] . "\t";
        echo $item['discount'] . "\t";
        echo $item_total . "\t";
        echo $status . "\n";
    }
    
    echo "\nBILL SUMMARY\n";
    echo "============\n";
    echo "Subtotal: Rs" . number_format($bill['subtotal'], 2) . "\n";
    echo "Total Discount: Rs" . number_format($bill['total_discount'], 2) . "\n";
    echo "Total Amount: Rs" . number_format($bill['total'], 2) . "\n";
    echo "Paid Amount: Rs" . number_format($bill['paid_amount'], 2) . "\n";
    echo "Balance: Rs" . number_format($bill['balance'], 2) . "\n\n";
    
    echo "Generated on: " . date('Y-m-d H:i:s') . "\n";
    echo "Generated by: " . $_SESSION['cashiers_id'] . "\n";
    
    exit();
}

$conn->close();
